web:
    build: docker/
    ports:
      - "80:80"
    links:
      - db
    volumes_from:
      - app

db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  volumes_from:
    - data
  environment:
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: camagru

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db

app:
  image: php:7.0-apache
  volumes: 
        - .:/var/www/html
  command: "true"

data:
    image: mysql
    volumes:
        - /var/lib/mysql
    command: "true"