<?php
define('PATH_ROOT', dirname(dirname(__DIR__)) . DIRECTORY_SEPARATOR);
define('PATH_APP', dirname(__DIR__) . DIRECTORY_SEPARATOR);

define('PATH_CONFIG', PATH_APP . 'config' . DIRECTORY_SEPARATOR);
define('PATH_COMPONENTS', PATH_APP . 'components' . DIRECTORY_SEPARATOR);

define('PATH_VIEWS', PATH_APP . 'views' . DIRECTORY_SEPARATOR);
define('PATH_MODELS', PATH_APP . 'models' . DIRECTORY_SEPARATOR);
define('PATH_CONTROLLERS', PATH_APP . 'controllers' . DIRECTORY_SEPARATOR);

define('PATH_HELPERS', PATH_APP . 'helpers' . DIRECTORY_SEPARATOR);
define ('PATH_EMAILS_CONTENT', PATH_HELPERS . 'emails' . DIRECTORY_SEPARATOR);

define('PATH_DB_MODELS', PATH_MODELS . 'db_models' . DIRECTORY_SEPARATOR);


define('PATH_WIDGETS', PATH_APP . 'widgets' . DIRECTORY_SEPARATOR);
define('PATH_WIDGETS_VIEWS', PATH_WIDGETS . 'views' . DIRECTORY_SEPARATOR);

define('PATH_VIEWS_FORMS', PATH_VIEWS . 'forms' . DIRECTORY_SEPARATOR);
define('PATH_VIEWS_FORMS_WIDGETS', PATH_VIEWS_FORMS . 'widgets' . DIRECTORY_SEPARATOR);


define('PATH_VIEWS_FORMS_CONFIG', PATH_VIEWS_FORMS . 'config' . DIRECTORY_SEPARATOR);
define('PATH_MODELS_FORMS_CONFIG', PATH_MODELS . 'forms/config' . DIRECTORY_SEPARATOR);
