<?php
define("PATH_ROOT", dirname(dirname(__DIR__)).DIRECTORY_SEPARATOR);
define("PATH_APP", dirname(__DIR__).DIRECTORY_SEPARATOR);

define("PATH_VIEWS", PATH_APP.'views'.DIRECTORY_SEPARATOR);
define("PATH_MODELS", PATH_APP.'models'.DIRECTORY_SEPARATOR);
define("PATH_CONTROLLERS", PATH_APP.'controllers'.DIRECTORY_SEPARATOR);


define("PATH_VIEWS_FORMS", PATH_VIEWS.'forms'.DIRECTORY_SEPARATOR);
define("PATH_VIEWS_FORMS_WIDGETS", PATH_VIEWS_FORMS.'widgets'.DIRECTORY_SEPARATOR);

define("PATH_CONFIG", PATH_APP.'config'.DIRECTORY_SEPARATOR);
define("PATH_VIEWS_FORMS_CONFIG", PATH_VIEWS_FORMS.'config'.DIRECTORY_SEPARATOR);
define("PATH_MODELS_FORMS_CONFIG", PATH_MODELS.'forms/config'.DIRECTORY_SEPARATOR);
